# Site settings
title: TurtlPass
email: hello@turtlpass.com
description: >- # this means to ignore newlines until "baseurl:"
  Where Passwords Swim Securely! Unleash Peace of Mind with Turtle-Approved Wisdom. Protecting You, Saving Turtles. ğŸ¢ğŸ’»
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://turtlpass.com" 

github_username: turtlpass

# Build settings
markdown: kramdown
